### ISSUE TITLE
`GraphSelectionModel` doesn't fire `CHANGE` event on selection change

### ISSUE THREAD

**Issue by mayorovad** [maxGraph/maxgraph#112]
Hi! 

Have issue with `GraphSelectionModel`. In mxGraph I added listeners to selection model like this
```typescript
graph.getSelectionModel().addListener(InternalEvent.CHANGE, (sender: EventSource, evt: EventObject) => {
      ...
});
```
But now it doesn't seem to work. I looked at code and found that now `CHANGE` event is fired to `graph` and not `selectionModel` like it`s used to be. 

https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/undoable_changes/SelectionChange.ts#L64-L66

Tried to replace `graph` with `selectionModel` and events started to fire as I expected.

This is how it used to be in mxGraph:
https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/view/mxGraphSelectionModel.js#L434-L435

It`s confusing me, because in examples listener added to selection model
https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/GraphSelectionModel.ts#L35-L43

**Comment by mayorovad** [comment]
Also, firing to `GraphSelectionModel` instead of `Graph` seems to break cell outline rendering. Adding listener to `GraphSelectionModel` here to call `updateHandler` fixed outline rendering.

https://github.com/maxGraph/maxGraph/blob/02ea6f1ceb398c2a6c08df7ecc52ee3d5efe46cc/packages/core/src/view/other/Outline.ts#L117-L125

**Comment by mcyph** [comment]
Strange that the first parameter to `SelectionChange` changed to `graph: Graph` from `selectionModel`.

I'm only speculating here, but maybe it was because a `graph` was passed to it in some cases, and it caused typing issues(?) Another alternative is someone (likely me) may have tried to tried to merge `selectionModel` methods with the `Graph` class, but I can't recall this. 

A large number of changes adding types across many files was made in a fairly short period of time, so there's every possibility it was a bug introduced in the midst of other things. I think it may pay to have a look at what else uses `SelectionChange` and make sure they mirror what the original mxGraph did, as there could be other issues which are related to this bug.

**Comment by mcyph** [comment]
Indeed, (now I've cloned maxGraph for the first time in a while and am able to more easily search) in `GraphSelectionModel.ts` `this.graph` is provided to `SelectionChange`, whereas it was just `this` in the original version of mxGraph (https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/src/js/view/mxGraphSelectionModel.js#L314):

```typescript
  /**
   * Adds/removes the specified arrays of {@link Cell} to/from the selection.
   *
   * @param added Array of {@link Cell} to add to the selection.
   * @param remove Array of {@link Cell} to remove from the selection.
   */
  changeSelection(added: Cell[] | null = null, removed: Cell[] | null = null) {
    if (
      (added && added.length > 0 && added[0]) ||
      (removed && removed.length > 0 && removed[0])
    ) {
      const change = new SelectionChange(this.graph, added || [], removed || []);
      change.execute();
      const edit = new UndoableEdit(this.graph, false);
      edit.add(change);
      this.fireEvent(new EventObject(InternalEvent.UNDO, { edit }));
    }
  }
```

Assuming it was me, I still don't have any idea why I would have done this. Perhaps it's possible to pass either `Graph` or `GraphSelectionModel` instances to `SelectionChange` constructors, when I thought it could only take `Graph`(?)
