### ISSUE TITLE
[LEGO] Q1 - How to make edge draggable? Is it possible to have example in story book?

### ISSUE THREAD

**Issue by lukasonokoleg** [maxGraph/maxgraph#136]
I am looking for an example - to configure edge behaviour similar/same - like in draw.io. How to make it draggable/reshable  - wihout loosing connection to the vertexes?

**Comment by mayorovad** [comment]
Hi @lukasonokoleg ! 

I believe that to make it draggable without loosing connection to vertex you need to call `Graph.setAllowDanglingEdges` method with `false` argument. For example, this method called in `Validation` story in Storybook, so you can check if it fits your needs.

About reshable edges - as you already know there is bug with handles rendering for segments of edges, which i hope is fixed by #120

**Comment by tbouffard** [comment]
Question answered so closing this issue
