### ISSUE TITLE
[LEGO] Q2 - How to enable endArrow - during edge preview stage? (new edge)

### ISSUE THREAD

**Issue by lukasonokoleg** [maxGraph/maxgraph#137]
Is it possible to have and example added to story book - which would show how to enable edge arrows - during preview - on first edge creation? (When edge is created - it is working fine)

**Comment by mayorovad** [comment]
Hi @lukasonokoleg !

The promblem is, shape that rendered for new connection preview doesn't support rendering arrows. In order to achieve that, you need to somehow change class of shape and add style for arrows you need. 

The metod you looking to override is `ConnectionHandler.createShape`. 
https://github.com/maxGraph/maxGraph/blob/27f75a59f3728ff2e592982121cdda4b7d36073a/packages/core/src/view/handler/ConnectionHandler.ts#L498-L515

For arrow to render, you need 

1. Replace `PolylineShape` with `ConnectorShape` , so change this https://github.com/maxGraph/maxGraph/blob/27f75a59f3728ff2e592982121cdda4b7d36073a/packages/core/src/view/handler/ConnectionHandler.ts#L503
to `: new ConnectorShape([], INVALID_COLOR, OUTLINE_STROKEWIDTH);`
2. Add style for shape (for example for end arrow to render) like `shape.style = {endArrow: ARROW.CLASSIC};`

**Comment by tbouffard** [comment]
Answer provided so closing this issue
