### ISSUE TITLE
Strongly recommend to be compatible with mxGraph@4.2.2

### ISSUE THREAD

**Issue by Hibop** [maxGraph/maxgraph#184]
After our effort of more than one month adapting maxGraph to mxGraph, we here strongly suggest that making mxGraph@4.2.2 to be compatible with maxGraph, or at least providing a compatible pollify layer (a tool) to ensure the stable running of the current 10000-lines code. Otherwise, the excellent refactoring library maxGraph cannot be widely used.

**Comment by tbouffard** [comment]
Hi @Hibop thanks for this feedback,

Could you share with us if you finally succeeded, what kind of problems or limitations you faced, .....
For unsolved issues, I suggest to open new GitHub issues and discussions to let us know and try to find solutions.

If you faced migration issues, or lack of guidance or documentation, I am very interesting in getting your insights. We started an initial version of a migration guide with is far for complete. I plan to work on it in the next months based on my own experience.
See https://github.com/maxGraph/maxGraph/blob/1447fd29fc0d2f2edb7f863850d2d38c6a17ed6c/packages/docs/migrate-from-mxgraph.md.


The compatibility with mxGraph has been widely discussed in the past. For instance, see https://github.com/maxGraph/maxGraph/issues/1#issuecomment-974312664 or #8.
A single thing emerged at that time. If there was a demand for it, we could create a maxGraph version to implement critical bug fixes for mxGraph 4.2.2. This could be done by creating a new repository in the maxGraph GitHub organization, something like `mxGraph-legacy` for example.
And eventually, if contributors want to make it evolves with new features, they would be free to do it. But don't forget that there are already few contributors to maxGraph. They will have even less time to maintain a version compatible with mxGraph. So, we should probably try to recruit new contributors for this as well.
As of today, no one has publicly expressed the need for this kind of support. So that's why, this initiative didn't start.
Please let us know if you would like this to happen.

**Comment by tbouffard** [comment]
No answer, so closing as part of an issue cleanup.
Feel free to recreate an new issue with more details.
