### ISSUE TITLE
getting error on edit of graph.

### ISSUE THREAD

**Issue by duke-arioch** [maxGraph/maxgraph#228]
When I double-click on editable node, I get the following:

this.graph.model.isEdge is not a function
TypeError: this.graph.model.isEdge is not a function
    at CellEditorHandler.startEditing 

Am I doing something wrong?

**Comment by Anthony-Wratpor** [comment]
isEdge() is meant to be directly used on a cell and not on the model itself, you should try to loop over this.graph.model.cells and then use isEdge() on the elements if you want to know if it's an edge or a vertex.

**Comment by duke-arioch** [comment]
the CellEditorHandler is not in my code. maxGraph itself is calling a nonexistent method on its own APIs.

I fixed this by adding in my code: GraphDataModel.prototype.isEdge = function (cell) {return false}

https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/handler/CellEditorHandler.ts#L805C22-L805C22

**Comment by tbouffard** [comment]
Hi, there is probably an issue in https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/core/src/view/handler/CellEditorHandler.ts#L804C9-L805
There is a ts-ignore directive because TypeScript correctly detects that GraphDataModel.isEdge doesn't exist and it is right. The method doesn't exist anymore (see https://github.com/maxGraph/maxGraph/blob/e25fd447be9ff3c02b877928ed17a615a4d77896/packages/docs/migrate-from-mxgraph.md#cell-manipulation). The comment from @Anthony-Wratpor is correct IMHO.

The fix should be something like `this.graph.model.isEdge(state.cell)` --> `state.cell.isEdge()`


If someone want to provide a fix, please drop a comment to let the world know 😄

**Comment by duke-arioch** [comment]
Interesting! I had just posted another item (query, not problem) - trying to better handle the graph as a view layer over an otherwise independent model of my own choosing. It feels like that may be less and less of the direction with this library. 

1. Is this correct?
2. If not then I eagerly await answer to other post :)
3. if it is true, does anyone have feedback how I might layer this on top?
