### ISSUE TITLE
Getting Started in Angular 13 not working

### ISSUE THREAD

**Issue by hermanfransen** [maxGraph/maxgraph#235]
I am trying to implement the getting started in an Angular 13 application. I followed the readme file, but I get the error:

Error: node_modules/@maxgraph/core/dist/types/gui/MaxPopupMenu.d.ts:29:15 - error TS2420: Class 'MaxPopupMenu' incorrectly implements interface 'Partial<PopupMenuItem>'.
  Types of property 'eventListeners' are incompatible.
    Type 'EventListenerObject[]' is not assignable to type '(eventName?: string) => EventListenerOrEventListenerObject[]'.
      Type 'EventListenerObject[]' provides no match for the signature '(eventName?: string): EventListenerOrEventListenerObject[]'.

29 declare class MaxPopupMenu extends EventSource implements Partial<PopupMenuItem> {

**Comment by tbouffard** [comment]
Hi @hermanfransen 
Are you using the latest version of maxGraph? Are you directly using __MaxPopupMenu__ in your code?
Which TypeScript version are you using?
Could you share a public repository to help to reproduce the issue?

The error is saying that a type is wrongly declared and this seems not relating to the integration of maxGraph in an Angular application 
We don't see this error in https://github.com/maxGraph/maxgraph-integration-examples whereas if the types were wrong, it will detect the errors as well. The projects in this repo use TypeScript 4.4 or 5.1.

Note: someone requested to have an Angular example, I am pretty sure that your work could help https://github.com/maxGraph/maxgraph-integration-examples/issues/20

**Comment by hermanfransen** [comment]
Hi,
Yes, I am using the latest version of maxGraph. No, I am not directly using the MaxPopupMenu in my code. I used the "getting started" code on the readme page. I am checking out the repo for the first time.
Here is the public library using Angular 13:
https://github.com/hermanfransen/max-graph-angular-test

You can check this out with:
- npm install
- npm start

Thanks for your help !!

**Comment by tbouffard** [comment]
Ok thanks for the repo, I will be able to give it a try.
It currently uses `typescript~4.6.2`

**Comment by tbouffard** [comment]
Hi @hermanfransen 
I have been able to reproduce the problem with your repository running in GitHub Codespace (ensure a fresh repro environment) when running `npm run build`.
I see the problem with TypeScript 4.5.4 and 4.6.4. I haven't been able to check with other versions because Angular doesn't support 4.7+ versions and the project requires TypeScript 4.5+ (due to usage of 4.5 features in various types).
I am trying to reproduce this behavior with the [examples](https://github.com/maxGraph/maxgraph-integration-examples) repository

**A side note** (it may help when the maxGraph type issue will be fixed): I have seen that you are currently declaring the Graph container with an id. https://github.com/hermanfransen/max-graph-angular-test/blob/9cc110cedb575f008f9566ccb6017ccb07bcecf7/src/app/app.component.ts#L14
AFAIK this won't work. You may probably use something like what it is done in https://github.com/Dhawaldeep/mxgraph-angular-tteen/blob/ef7166aa0596ade96c0dd8fd03e09ad68c7f724e/src/app/app.component.html and use with https://github.com/Dhawaldeep/mxgraph-angular-tteen/blob/7ba3e9cb1609e7c8d57498e3d7878e2be634c91a/src/app/app.component.ts#L10-L11

**Comment by hermanfransen** [comment]
Hi [tbouffard](https://github.com/tbouffard),
Thanks for your effect.

**Comment by tbouffard** [comment]
In the meantime you can use https://www.typescriptlang.org/tsconfig#skipLibCheck to temporarily hide the error and move forward with the integration of maxGraph in the angular getting started.

I will try to investigate the problem in the next days because it may impact users using other frameworks as well.

**Comment by tbouffard** [comment]
New try today with the reproduction repository, still not working even when bumping dependencies
- @maxgraph/core 0.3.0 to 0.6.0
- tslib 2.3.0 to 2.6.2
- typescript 4.6.4

**Comment by tbouffard** [comment]
Removing the implements Partial in the class declaration fix the type error.
This clause has been introduced in 61648e43 and seems not needed.

The following fix the problem in the repro repo:
```typescript
declare class MaxPopupMenu extends EventSource {
// declare class MaxPopupMenu extends EventSource implements Partial<PopupMenuItem> {
```
