### ISSUE TITLE
Does anyone have a tutorial on how to get started with this?

### ISSUE THREAD

**Issue by asgharhussaindev** [maxGraph/maxgraph#250]
Hello, I am trying to use this library to generate some graphics, but am unable to get NPM to work with it. I get basic errors like:

    $ node example1.js 
    file:///Users/ah/ComputerProgramming/MaxGraph/Examples/example1.js:1
    import {type CellStyle, Graph, InternalEvent} from '@maxgraph/core';
                          ^^^^^^^^^

    SyntaxError: Unexpected identifier
        at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
        at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
        at async link (node:internal/modules/esm/module_job:67:21)

I am confused whether this is ESM or CommonJS. Any tips for a beginner would be greatly appreciated.

**Comment by tbouffard** [comment]
Hi @asgharhussaindev 
About your issue
- you are using the TypeScript syntax (the `type` keyword in the import directive) in a JavaScript file, this is why you get a syntax error
- the @maxGraph/core package currently provides both ESM and UMD (so CommonJS) flavors. Please prefer the usage of ESM as the UMD bundle will be probably removed in a near future
- maxGraph is intended to be used in the browser, so including maxGraph in a node script is probably not what you want to do. Notice that this is possible and it works (it is done in the low-level tests of the project)


About a getting started
- there are dedicated paragraphs available in the README of the repository about the [installation](https://github.com/maxGraph/maxGraph/blob/v0.4.0/README.md#install) and a quick [getting started guide](https://github.com/maxGraph/maxGraph/blob/v0.4.0/README.md#getting-started)
- the code is for TypeScript but doesn't mention it, so I can add a statement to warn readers. There is also a link that mentions the Storybook examples (which are currently written in JavaScript)
- the mxGraph documentation has not been migrated for now, when it will be done, it will contain a more detailed getting started and more examples
- the README includes in the [npm package](https://github.com/maxGraph/maxGraph/blob/v0.4.0/packages/core/README.md) doesn't mention all this information for now. As a short term improvement, I can add a link to the repository README to let users access the more detailed information.
- what would you expect to find in the getting started? Your feedback will help to improve the documentation


Next time, please use the [Q&A](https://github.com/maxGraph/maxGraph/discussions/categories/q-a) instead of the issue tracker for such a question. This allows to keep the "GitHub issues" for bug and feature requests.

**Comment by asgharhussaindev** [comment]
Thank you for your comments. A full browser HTML example would help new users like me.

**Comment by tbouffard** [comment]
> Thank you for your comments. A full browser HTML example would help new users like me.

Can you be more specific about what you have in mind?

If you're thinking of a single HTML page loading `maxGraph` and custom code, no such page exists. AFAIK, there has been no traction for this.

Several examples exist that show how to integrate `maxGraph` into applications running in the browser:
- https://github.com/maxGraph/maxGraph/tree/v0.4.0/packages/ts-example
- https://github.com/maxGraph/maxgraph-integration-examples

They probably deserve to be given more prominence. I'll update the README soon.

**Comment by asgharhussaindev** [comment]
Thank you for posting the examples. I plan to try them on the weekend and will report back as to whether it worked or not.

**Comment by tbouffard** [comment]
Fine.
In the mean time I will create a Pull Request to improve the documentation.

**Comment by asgharhussaindev** [comment]
Hi,

I tried the example at https://github.com/maxGraph/maxGraph/tree/v0.4.0/packages/ts-example, but I can't connect to anything on http://localhost:5173

Running "netstat" shows no open sockets tied to port 5173. Any ideas? Output below:

[ah@mbp:/Users/ah/ComputerProgramming/maxGraph/packages/core] 
$ npm run dev 

> @maxgraph/core@0.4.0 dev
> webpack --watch --mode=development

asset maxgraph.js 8.77 MiB [compared for emit] (name: main)
runtime modules 670 bytes 3 modules
modules by path ./src/view/ 2.31 MiB 143 modules
modules by path ./src/util/*.ts 185 KiB 21 modules
modules by path ./src/gui/*.ts 97.9 KiB
  ./src/gui/MaxLog.ts 11.7 KiB [built] [code generated]
  + 4 modules
modules by path ./src/editor/*.ts 157 KiB
  ./src/editor/EditorKeyHandler.ts 10.2 KiB [built] [code generated]
  + 3 modules
modules by path ./src/*.ts 24.1 KiB
  ./src/index.ts 12.5 KiB [built] [code generated]
  + 2 modules
modules by path ./src/serialization/*.ts 56.8 KiB
  ./src/serialization/ObjectCodec.ts 34 KiB [built] [code generated]
  + 2 modules
webpack 5.88.2 compiled successfully in 4633 ms

**Comment by asgharhussaindev** [comment]
Never mind the above. I was able to run the Storybook from the main directory. Looks pretty good.

My use case will be very simple and this is just one example. I have an algorithm that generates SPF (Shortest Path First) problems, or binary tree problems, or red/black tree problems. You get the idea. Now I want to show these in a diagram so they can be explained to others. That is essentially my use case for now. So how can I integrate maxGraph as a library in a project such that I make calls to maxGraph, providing it all the information necessary for generating a diagram (take binary trees as the simplest example) and then being able to generate said diagram.

**Comment by tbouffard** [comment]
> Running "netstat" shows no open sockets tied to port 5173. Any ideas? Output below:
[ah@mbp:/Users/ah/ComputerProgramming/maxGraph/packages/core] $ npm run dev
@maxgraph/core@0.4.0 dev webpack --watch --mode=development

You are running the command from `packages/core` instead of `packages/ts-example` so you are just building maxGraph instead of starting the dev server of the demo.

> So how can I integrate maxGraph as a library in a project such that I make calls to maxGraph, ….

Please create a dedicated question in the [Q&A](https://github.com/maxGraph/maxGraph/discussions/categories/q-a) as it is not related to your initial problem.
This helps keeping things clear for users.

If you don’t have other questions about the getting started thing, I will close this issue and I will create a documentation PR to improve the README.

**Comment by asgharhussaindev** [comment]
Thank you for your help. I think some people would want to use this project to generate diagrams/graphs on a similar line to what I am trying to do. Please proceed to close and I will try and open a question in Q&A as per your suggestion.
