### ISSUE TITLE
GraphDataModel.isLayer: cannot read properties of null (reading 'getParent')

### ISSUE THREAD

**Issue by Duoladuola** [maxGraph/maxgraph#357]
If the parameter "cell" is "null", "null" is returned in the earlier version while an error is reported in the new version.

**report error:**
![image](https://github.com/maxGraph/maxGraph/assets/56530965/b31fb32f-9de8-4b1d-8d15-0fa0a654dd89)

**old version will return "null":**
![image](https://github.com/maxGraph/maxGraph/assets/56530965/ead645e1-ae01-4bb8-8393-ecebcbfadfdb)

**Comment by tbouffard** [comment]
Hi @Duoladuola 
I remember that during the migration from mxGraph, some null checks have been removed because they were considered as extra checks.
Some were probably removed by mistake, for example in the case you detected.

mxGraphModel.getParent in mxGraph 4.2.2: https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/model/mxGraphModel.js#L591-L603. This method no longer exists maxGraph.

If someone wants to contribute a fix for this, feel free to open a Pull Request and don't forget to add automatic tests (this is quite an easy use case to test, and to also test the nominal case - defined Cell).

**Comment by eRedekopp** [comment]
I will work on this!
