### ISSUE TITLE
The performance of the getCell method of the CollectionHandler class is different from that of the old version after migration.

### ISSUE THREAD

**Issue by Duoladuola** [maxGraph/maxgraph#362]
### In maxGraph0.8., When ` this.connectionHandler.error `equals empty string，`this.connectionHandler.error && this.connectionHandler.error.length === 0`equals `false`
![image](https://github.com/maxGraph/maxGraph/assets/56530965/7fa8b14c-264c-4ab3-908e-8df46632e274)

###  But in the old version, the value of this expression（`this.error != null && this.error.length == 0`） was `true`

![image](https://github.com/maxGraph/maxGraph/assets/56530965/829e5479-9231-4e5f-958a-8904bb5414c9)
### This is the result of the expression running on the console，the result is `true`
![image](https://github.com/maxGraph/maxGraph/assets/56530965/8ef7e39a-b8d3-419e-aa1f-7318ac5893cb)
### I made a fix in my project to keep the original functionality. If Return values for `validateConnection ` is an empty string, I will use an empty array instead.
this.graph.getPlugin('ConnectionHandler').validateConnection = function(source, target) {
    let error = null;
    if (!this.isValidTarget(target)) {
        error = '';
    }
    error = this.graph.getEdgeValidationError(null, source, target);
    return error === '' ? [] : error;
}

**Comment by eRedekopp** [comment]
This appears to be an error in the code. Since `""` is falsy, the statement will be false when `this.error` is an empty string even though that is clearly what the if-statement is looking for. This line has existed since version 0.1.0 and seems to have been a mistake in translating to TS.

I'm a little bit unclear on why we only want to run the if-statement if the string is specifically present and empty but not null, rather than when it is either empty or null. It seems to me that it would make the most sense to simply put `if (!this.error)` to cover both cases, but I could be missing some important details. Either way, we could easily fix this by reverting to the old version `if (this.error !== null && this.error.length === 0)`

I will follow up and look into why we might want to exclude the case where `this.error` is null, and submit a PR within the next couple days with whichever of the two above solutions makes the most sense.

**Comment by eRedekopp** [comment]
Can't use `(!this.error)` because empty error message specifically means that the connection target was invalid. Fixed and made a PR.
