### ISSUE TITLE
[BUG] Submenu image is not displayed

### ISSUE THREAD

**Issue by sakairy** [maxGraph/maxgraph#404]
### Describe the bug
Submenu image is not displayed. (like ▶)
Fail to get imege.

### To Reproduce
Open menu including submenu.

[Storybook](https://maxgraph.github.io/maxGraph/demo/?path=/story/misc-menustyle--default)
[mywork(angular)](https://stackblitz.com/~/github.com/sakairy/angular_practice)(code is almost same to storybook)

### Expected behavior
imege is displayed.

### Environment
I saw on firefox and chrome.

### Additional context
It may be good idea to replece `<img>`  to  `<svg>`.

**Comment by tbouffard** [comment]
Using the demo deployed on GitHub Pages, the image doesn't display because the path to the image is incorrect: https://maxgraph.github.io/maxGraph/demo/submenu.gif. It should be https://maxgraph.github.io/maxGraph/demo/images/submenu.gif

https://github.com/maxGraph/maxGraph/blob/3b84bf2dca13bac881bdb6450308091a65fc0e46/packages/core/src/gui/MaxPopupMenu.ts#L91
`Client.imageBasePath` should be configured by calling the `configureImagesBasePath` function in the story as it is done in other stories.


> It may be good idea to replece `<img>`  to  `<svg>`.

There is currently no plan to change the usage of the GIF. 
But it is possible to update the path to the image by setting `MaxPopupMenu.submenuImage`
